spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.97.8.230:5432/npi-pss?currentSchema=public
    username: postgres
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

